// <auto-generated />
namespace Sneat.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class updatedobuserdetail : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updatedobuserdetail));
        
        string IMigrationMetadata.Id
        {
            get { return "202407260637289_update-dob-user-detail"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
