// <auto-generated />
namespace Sneat.MVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class userdetailtable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(userdetailtable));
        
        string IMigrationMetadata.Id
        {
            get { return "202407221647474_user-detail table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
